FROM node:16

WORKDIR /code

COPY . .

#COPY package.json .
#COPY package-lock.json .

RUN npm install -g @vue/cli

#RUN vue create project_resource_planning

CMD ["/bin/bash"]


#CMD ["npm", "run", "serve"]
