version: '3'

services:
  backend:
    build:
      context: ./backend
    entrypoint: /entrypoint/entrypoint.sh
    volumes:
      - ./backend:/code
      - ./docker/django/entrypoint.sh:/entrypoint/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://root:password@database:3306/db_name

  frontend:
    build:
      context: ./docker/frontend
    volumes:
      - ./frontend:/code
    ports:
      - "8080:8080"

  database:
    image: mariadb
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_name
